source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ctinusDev/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'TMFileManager_Example' do
  pod 'TMFileManager', :path => '../'
  target 'TMFileManager_Tests' do
    inherit! :search_paths

    
  end
end
